version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=wohnungen

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wohnungen
    volumes:
      - db_data:/var/lib/mysql
      - ./wohnungen.sql:/docker-entrypoint-initdb.d/wohnungen.sql
volumes:
  db_data:
